### ISSUE TITLE
[BUG] Unable to generate OpenAPI3.0 specification. It is coming Blank

### ISSUE THREAD

**Issue by Siddharth084** [WillEastbury/odata-openapi#7]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

** OData Payload for diagnosis **
Please paste or link to your odata payload that was processed.

**Additional context**

**Comment by MartinPankraz** [comment]
@Siddharth084 please shared details of your request.

**Comment by MartinPankraz** [comment]
duplicate of #8
